version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sweat-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${ORM_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${ORM_PASSWORD:-postgres}
      POSTGRES_DB: ${ORM_DB:-sweat_api}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sweat-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Uncomment if you want to include MinIO as a local S3-compatible storage service
  # minio:
  #   image: minio/minio
  #   container_name: sweat-minio
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   environment:
  #     MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID:-minioadmin}
  #     MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY:-minioadmin}
  #   volumes:
  #     - minio_data:/data
  #   command: server --console-address ":9001" /data
  #   networks:
  #     - sweat-network
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3

  # Uncomment to include pgAdmin for database management
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: sweat-pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - sweat-network
  #   depends_on:
  #     - postgres

networks:
  sweat-network:
    driver: bridge

volumes:
  postgres_data:
  # minio_data: