version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: sweat-api-test-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sweat_api_test
    ports:
      - "5432:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    networks:
      - test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  firebase-emulator:
    image: andreysenov/firebase-tools:latest
    container_name: sweat-api-test-firebase
    ports:
      - "9099:9099"  # Auth
      - "4000:4000"  # Emulator UI
    volumes:
      - ./firebase.json:/home/node/firebase.json
      - ./firebase-data:/home/node/firebase-data
      - ./storage.rules:/home/node/storage.rules
    environment:
      - FIREBASE_PROJECT_ID=sweat-api-test
    entrypoint: firebase emulators:start --project sweat-api-test
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 5s
      timeout: 10s
      retries: 3

networks:
  test-network:
    driver: bridge

volumes:
  postgres-test-data: