export enum SOCIAL {
  COMMENT = 'COMMENT',
  REPLY = 'REPLY',
  REACT = 'REACT',
  CREATE_FRIEND_REQUEST = 'CREATE_FRIEND_REQUEST',
  ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST',
  TEST_NOTIFICATION = 'TEST_NOTIFICATION',
  FOLLOW_POST_CREATE = 'FOLLOW_POST_CREATE',
  FOLLOW_POST_LIKE = 'FOLLOW_POST_LIKE',
  FOLLOW_POST_COMMENT = 'FOLLOW_POST_COMMENT',
}
