name: Deploy Sweat API

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      GIT_SHA: ${{ steps.get_sha.outputs.GIT_SHA }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send Telegram notification on deployment start
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 Deployment Started!
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Initiated by: ${{ github.actor }}

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Get short Git SHA
        id: get_sha
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV && echo "::set-output name=GIT_SHA::$(git rev-parse --short HEAD)"

      - name: Build and tag Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/sweat-api:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/sweat-api:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      GIT_SHA: ${{ needs.build-and-push.outputs.GIT_SHA }}
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ssm get-parameter --name "sweat" --with-decryption --query "Parameter.Value" --output text --region ap-southeast-1 > .env
            docker pull ${{ secrets.DOCKER_USERNAME }}/sweat-api:latest

            # Stop and remove the container if it exists
            docker stop sweat-api || true
            docker rm sweat-api || true

            # Run the new container
            docker run -d --name sweat-api -p 80:3000 --env-file .env --restart always ${{ secrets.DOCKER_USERNAME }}/sweat-api:latest

      - name: Send Telegram notification on success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ Deployment Successful!
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ needs.build-and-push.outputs.GIT_SHA }}
            Deployed by: ${{ github.actor }}
            See details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Send Telegram notification on failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ❌ Deployment Failed!
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ needs.build-and-push.outputs.GIT_SHA }}
            Initiated by: ${{ github.actor }}
            See details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
